remove test git project

diff --git a/pre-build b/pre-build
--- a/pre-build
+++ b/pre-build
@@ -79,15 +79,13 @@ cat << EOT > pom.xml
 </project>
 EOT
 
-mvn --batch-mode versions:use-latest-releases 1>stdout.txt 2>stderr.txt
+mvn --batch-mode --log-file output.txt versions:use-latest-releases
 result=$?
 if [ ! ${result} == 0 ]; then
     echo "Error: $0[${LINENO}]"
     echo "result: ${result}"
-    echo "----[ stdout ]--------------------------"
-    cat stdout.txt
-    echo "----[ stderr ]--------------------------"
-    cat stderr.txt
+    echo "----[ output.txt ]--------------------------"
+    cat output.txt
     echo "----------------------------------------"
     exit 1
 fi
@@ -149,6 +147,35 @@ done
 #*****************************************************************
 # Update the version
 #*****************************************************************
-mvn versions:set -DnewVersion=${BUILD_ID}
-mvn versions:use-dep-version -DdepVersion=${utilities_version} -Dincludes=com.rsmaxwell.utilities:utilities
-mvn versions:use-latest-releases
+mvn --batch-mode --log-file output.txt versions:set -DnewVersion=${BUILD_ID}
+result=$?
+if [ ! ${result} == 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    echo "----[ output.txt ]--------------------------"
+    cat output.txt
+    echo "----------------------------------------"
+    exit 1
+fi
+
+mvn --batch-mode --log-file output.txt versions:use-dep-version -DdepVersion=${utilities_version} -Dincludes=com.rsmaxwell.utilities:utilities
+result=$?
+if [ ! ${result} == 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    echo "----[ output.txt ]--------------------------"
+    cat output.txt
+    echo "----------------------------------------"
+    exit 1
+fi
+
+mvn --batch-mode --log-file output.txt versions:use-latest-releases
+result=$?
+if [ ! ${result} == 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    echo "----[ output.txt ]--------------------------"
+    cat output.txt
+    echo "----------------------------------------"
+    exit 1
+fi
